// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package local.example.care.customer.api.grpc.v1;

public interface CustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.care.customer.api.v1.Customer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.google.protobuf.Timestamp created = 2;</code>
   * @return Whether the created field is set.
   */
  boolean hasCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 2;</code>
   * @return The created.
   */
  com.google.protobuf.Timestamp getCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string surname = 4;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 4;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>.local.example.care.customer.api.v1.Customer.Status status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.local.example.care.customer.api.v1.Customer.Status status = 5;</code>
   * @return The status.
   */
  local.example.care.customer.api.grpc.v1.Customer.Status getStatus();
}
