// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package local.example.care.customer.api.grpc.v1;

public final class CustomerOuterClass {
  private CustomerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_customer_api_v1_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_customer_api_v1_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_customer_api_v1_Customer_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_customer_api_v1_Customer_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_customer_api_v1_Customer_EContact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_customer_api_v1_Customer_EContact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_customer_api_v1_CustomerCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_customer_api_v1_CustomerCreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Customer.proto\022\"local.example.care.cus" +
      "tomer.api.v1\032\037google/protobuf/timestamp." +
      "proto\"\364\002\n\010Customer\022\n\n\002id\030\001 \001(\003\022+\n\007create" +
      "d\030\002 \001(\0132\032.google.protobuf.Timestamp\022\014\n\004n" +
      "ame\030\003 \001(\t\022\017\n\007surname\030\004 \001(\t\022C\n\006status\030\005 \001" +
      "(\01623.local.example.care.customer.api.v1." +
      "Customer.Status\032q\n\007Address\022\r\n\005civic\030\001 \001(" +
      "\t\022\016\n\006street\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022\r\n\005state" +
      "\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\031\n\021postalIndexNu" +
      "mber\030\006 \001(\t\0328\n\010EContact\022\r\n\005phone\030\001 \001(\t\022\016\n" +
      "\006mobile\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"\036\n\006Status\022\n" +
      "\n\006ACTIVE\020\000\022\010\n\004IDLE\020\001\"$\n\026CustomerCreateRe" +
      "sponse\022\n\n\002id\030\001 \001(\0032\205\001\n\017CustomerService\022r" +
      "\n\006Create\022,.local.example.care.customer.a" +
      "pi.v1.Customer\032:.local.example.care.cust" +
      "omer.api.v1.CustomerCreateResponseB+\n\'lo" +
      "cal.example.care.customer.api.grpc.v1P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_local_example_care_customer_api_v1_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_local_example_care_customer_api_v1_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_customer_api_v1_Customer_descriptor,
        new java.lang.String[] { "Id", "Created", "Name", "Surname", "Status", });
    internal_static_local_example_care_customer_api_v1_Customer_Address_descriptor =
      internal_static_local_example_care_customer_api_v1_Customer_descriptor.getNestedTypes().get(0);
    internal_static_local_example_care_customer_api_v1_Customer_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_customer_api_v1_Customer_Address_descriptor,
        new java.lang.String[] { "Civic", "Street", "City", "State", "Country", "PostalIndexNumber", });
    internal_static_local_example_care_customer_api_v1_Customer_EContact_descriptor =
      internal_static_local_example_care_customer_api_v1_Customer_descriptor.getNestedTypes().get(1);
    internal_static_local_example_care_customer_api_v1_Customer_EContact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_customer_api_v1_Customer_EContact_descriptor,
        new java.lang.String[] { "Phone", "Mobile", "Email", });
    internal_static_local_example_care_customer_api_v1_CustomerCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_local_example_care_customer_api_v1_CustomerCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_customer_api_v1_CustomerCreateResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
