// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carrier.proto

package local.example.care.carrier.api.grpc.v1;

public final class CarrierOuterClass {
  private CarrierOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_carrier_api_v1_Carrier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_carrier_api_v1_Carrier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_carrier_api_v1_Carrier_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_carrier_api_v1_Carrier_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_carrier_api_v1_Carrier_EContact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_carrier_api_v1_Carrier_EContact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_local_example_care_carrier_api_v1_CarrierCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_local_example_care_carrier_api_v1_CarrierCreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcarrier.proto\022!local.example.care.carr" +
      "ier.api.v1\032\037google/protobuf/timestamp.pr" +
      "oto\"\375\001\n\007Carrier\022\n\n\002id\030\001 \001(\003\022+\n\007created\030\002" +
      " \001(\0132\032.google.protobuf.Timestamp\022\014\n\004name" +
      "\030\003 \001(\t\032q\n\007Address\022\r\n\005civic\030\001 \001(\t\022\016\n\006stre" +
      "et\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022\r\n\005state\030\004 \001(\t\022\017\n" +
      "\007country\030\005 \001(\t\022\031\n\021postalIndexNumber\030\006 \001(" +
      "\t\0328\n\010EContact\022\r\n\005phone\030\001 \001(\t\022\016\n\006mobile\030\002" +
      " \001(\t\022\r\n\005email\030\003 \001(\t\"#\n\025CarrierCreateResp" +
      "onse\022\n\n\002id\030\001 \001(\0032\200\001\n\016CarrierService\022n\n\006C" +
      "reate\022*.local.example.care.carrier.api.v" +
      "1.Carrier\0328.local.example.care.carrier.a" +
      "pi.v1.CarrierCreateResponseB*\n&local.exa" +
      "mple.care.carrier.api.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_local_example_care_carrier_api_v1_Carrier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_local_example_care_carrier_api_v1_Carrier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_carrier_api_v1_Carrier_descriptor,
        new java.lang.String[] { "Id", "Created", "Name", });
    internal_static_local_example_care_carrier_api_v1_Carrier_Address_descriptor =
      internal_static_local_example_care_carrier_api_v1_Carrier_descriptor.getNestedTypes().get(0);
    internal_static_local_example_care_carrier_api_v1_Carrier_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_carrier_api_v1_Carrier_Address_descriptor,
        new java.lang.String[] { "Civic", "Street", "City", "State", "Country", "PostalIndexNumber", });
    internal_static_local_example_care_carrier_api_v1_Carrier_EContact_descriptor =
      internal_static_local_example_care_carrier_api_v1_Carrier_descriptor.getNestedTypes().get(1);
    internal_static_local_example_care_carrier_api_v1_Carrier_EContact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_carrier_api_v1_Carrier_EContact_descriptor,
        new java.lang.String[] { "Phone", "Mobile", "Email", });
    internal_static_local_example_care_carrier_api_v1_CarrierCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_local_example_care_carrier_api_v1_CarrierCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_local_example_care_carrier_api_v1_CarrierCreateResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
