// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carrier.proto

package local.example.care.carrier.api.grpc.v1;

public interface CarrierCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.care.carrier.api.v1.CarrierCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
