openapi: "3.1.0"
info:
  version: 0.0.1-SNAPSHOT
  title: Pet-Clinic
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /patients:
    get:
      summary: Pet clinic database API
      operationId: listOfLittlePatients
      tags:
        - patients
      parameters:
        - name: limit
          in: query
          description: How many patients to return at one time
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pet-clinic patients
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patients"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a patient
      operationId: toRecordPatients
      tags:
        - patients
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /patients/{patientId}:
    get:
      summary: Info for a specific patient
      operationId: showPatientById
      tags:
        - patients
      parameters:
        - name: patientId
          in: path
          required: true
          description: The id of the patientt to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patient"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Patient:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Patients:
      type: array
      items:
        $ref: "#/components/schemas/Patient"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
