CREATE MEMORY TABLE "PUBLIC"."addresses"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "city" VARCHAR_IGNORECASE(255),
    "country" VARCHAR_IGNORECASE(255),
    "number" VARCHAR_IGNORECASE(255),
    "residential" BOOLEAN,
    "state" VARCHAR_IGNORECASE(255),
    "street" VARCHAR_IGNORECASE(255),
    "town" VARCHAR_IGNORECASE(255),
    "zipcode" VARCHAR_IGNORECASE(255)
);
ALTER TABLE "PUBLIC"."addresses" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."authorizations"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "authorized" BOOLEAN,
    "error" VARCHAR_IGNORECASE(255),
    "message" VARCHAR_IGNORECASE(255)
);
ALTER TABLE "PUBLIC"."authorizations" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."cards"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "csc" VARCHAR_IGNORECASE(255),
    "expires" VARCHAR_IGNORECASE(255),
    "number" VARCHAR_IGNORECASE(255)
);
ALTER TABLE "PUBLIC"."cards" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."carts"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "joined" BOOLEAN DEFAULT TRUE
);
ALTER TABLE "PUBLIC"."carts" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5A" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."correlations"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL
);
ALTER TABLE "PUBLIC"."correlations" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_51" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."customers"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "active" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."customers" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."forwarders"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "active" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."forwarders" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."items"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "available" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."items" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5F" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."orders"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "processed" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."orders" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."payments"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "paid" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."payments" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_52" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."products"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "available" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."products" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."shipments"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "achieve" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."shipments" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."suppliers"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "active" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."suppliers" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FE" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."tags"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL
);
ALTER TABLE "PUBLIC"."tags" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_36" PRIMARY KEY("id");

CREATE MEMORY TABLE "PUBLIC"."users"(
    "id" VARCHAR_IGNORECASE(255) NOT NULL,
    "registered" TIMESTAMP NOT NULL,
    "updated" TIMESTAMP NOT NULL,
    "active" BOOLEAN DEFAULT FALSE
);
ALTER TABLE "PUBLIC"."users" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6A" PRIMARY KEY("id");
