// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>string residency = 3;</code>
   * @return The residency.
   */
  java.lang.String getResidency();
  /**
   * <code>string residency = 3;</code>
   * @return The bytes for residency.
   */
  com.google.protobuf.ByteString
      getResidencyBytes();

  /**
   * <code>string street = 4;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 4;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string city = 5;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 5;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 6;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 6;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string country = 7;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 7;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string postalCode = 8;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <code>string postalCode = 8;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();
}
