// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface AttachOrDetachReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.AttachOrDetachReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sourceId = 1;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string sourceId = 1;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string customerId = 2;</code>
   * @return The customerId.
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customerId = 2;</code>
   * @return The bytes for customerId.
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();
}
