// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface CaptureChargeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.CaptureChargeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string chargeId = 1;</code>
   * @return The chargeId.
   */
  java.lang.String getChargeId();
  /**
   * <code>string chargeId = 1;</code>
   * @return The bytes for chargeId.
   */
  com.google.protobuf.ByteString
      getChargeIdBytes();

  /**
   * <code>uint32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();

  /**
   * <code>string receiptEmail = 3;</code>
   * @return The receiptEmail.
   */
  java.lang.String getReceiptEmail();
  /**
   * <code>string receiptEmail = 3;</code>
   * @return The bytes for receiptEmail.
   */
  com.google.protobuf.ByteString
      getReceiptEmailBytes();

  /**
   * <code>string statementDescriptor = 4;</code>
   * @return The statementDescriptor.
   */
  java.lang.String getStatementDescriptor();
  /**
   * <code>string statementDescriptor = 4;</code>
   * @return The bytes for statementDescriptor.
   */
  com.google.protobuf.ByteString
      getStatementDescriptorBytes();
}
