// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface CardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.Card)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.local.example.sample.api.grpc.v1.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.local.example.sample.api.grpc.v1.Address address = 3;</code>
   * @return The address.
   */
  local.example.sample.api.grpc.v1.Address getAddress();
  /**
   * <code>.local.example.sample.api.grpc.v1.Address address = 3;</code>
   */
  local.example.sample.api.grpc.v1.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>string brand = 4;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 4;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>string country = 5;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 5;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>uint32 expMonth = 6;</code>
   * @return The expMonth.
   */
  int getExpMonth();

  /**
   * <code>uint32 expYear = 7;</code>
   * @return The expYear.
   */
  int getExpYear();

  /**
   * <code>string fingerprint = 8;</code>
   * @return The fingerprint.
   */
  java.lang.String getFingerprint();
  /**
   * <code>string fingerprint = 8;</code>
   * @return The bytes for fingerprint.
   */
  com.google.protobuf.ByteString
      getFingerprintBytes();

  /**
   * <code>string funding = 9;</code>
   * @return The funding.
   */
  java.lang.String getFunding();
  /**
   * <code>string funding = 9;</code>
   * @return The bytes for funding.
   */
  com.google.protobuf.ByteString
      getFundingBytes();

  /**
   * <code>uint32 installments = 10;</code>
   * @return The installments.
   */
  int getInstallments();

  /**
   * <code>string last4 = 11;</code>
   * @return The last4.
   */
  java.lang.String getLast4();
  /**
   * <code>string last4 = 11;</code>
   * @return The bytes for last4.
   */
  com.google.protobuf.ByteString
      getLast4Bytes();

  /**
   * <code>string customer = 12;</code>
   * @return The customer.
   */
  java.lang.String getCustomer();
  /**
   * <code>string customer = 12;</code>
   * @return The bytes for customer.
   */
  com.google.protobuf.ByteString
      getCustomerBytes();
}
