// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface OwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.Owner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.local.example.sample.api.grpc.v1.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.local.example.sample.api.grpc.v1.Address address = 1;</code>
   * @return The address.
   */
  local.example.sample.api.grpc.v1.Address getAddress();
  /**
   * <code>.local.example.sample.api.grpc.v1.Address address = 1;</code>
   */
  local.example.sample.api.grpc.v1.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string phone = 4;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 4;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>.local.example.sample.api.grpc.v1.Address verifiedAddress = 5;</code>
   * @return Whether the verifiedAddress field is set.
   */
  boolean hasVerifiedAddress();
  /**
   * <code>.local.example.sample.api.grpc.v1.Address verifiedAddress = 5;</code>
   * @return The verifiedAddress.
   */
  local.example.sample.api.grpc.v1.Address getVerifiedAddress();
  /**
   * <code>.local.example.sample.api.grpc.v1.Address verifiedAddress = 5;</code>
   */
  local.example.sample.api.grpc.v1.AddressOrBuilder getVerifiedAddressOrBuilder();

  /**
   * <code>string verifiedEmail = 6;</code>
   * @return The verifiedEmail.
   */
  java.lang.String getVerifiedEmail();
  /**
   * <code>string verifiedEmail = 6;</code>
   * @return The bytes for verifiedEmail.
   */
  com.google.protobuf.ByteString
      getVerifiedEmailBytes();

  /**
   * <code>string verifiedName = 7;</code>
   * @return The verifiedName.
   */
  java.lang.String getVerifiedName();
  /**
   * <code>string verifiedName = 7;</code>
   * @return The bytes for verifiedName.
   */
  com.google.protobuf.ByteString
      getVerifiedNameBytes();

  /**
   * <code>string verifiedPhone = 8;</code>
   * @return The verifiedPhone.
   */
  java.lang.String getVerifiedPhone();
  /**
   * <code>string verifiedPhone = 8;</code>
   * @return The bytes for verifiedPhone.
   */
  com.google.protobuf.ByteString
      getVerifiedPhoneBytes();
}
