// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface PaymentMethodDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.PaymentMethodDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.local.example.sample.api.grpc.v1.Card card = 1;</code>
   * @return Whether the card field is set.
   */
  boolean hasCard();
  /**
   * <code>.local.example.sample.api.grpc.v1.Card card = 1;</code>
   * @return The card.
   */
  local.example.sample.api.grpc.v1.Card getCard();
  /**
   * <code>.local.example.sample.api.grpc.v1.Card card = 1;</code>
   */
  local.example.sample.api.grpc.v1.CardOrBuilder getCardOrBuilder();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.local.example.sample.api.grpc.v1.SampleBrandAccount sampleBrandAccount = 3;</code>
   * @return Whether the sampleBrandAccount field is set.
   */
  boolean hasSampleBrandAccount();
  /**
   * <code>.local.example.sample.api.grpc.v1.SampleBrandAccount sampleBrandAccount = 3;</code>
   * @return The sampleBrandAccount.
   */
  local.example.sample.api.grpc.v1.SampleBrandAccount getSampleBrandAccount();
  /**
   * <code>.local.example.sample.api.grpc.v1.SampleBrandAccount sampleBrandAccount = 3;</code>
   */
  local.example.sample.api.grpc.v1.SampleBrandAccountOrBuilder getSampleBrandAccountOrBuilder();
}
