// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface ReceiverOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.Receiver)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>uint32 amountCharged = 2;</code>
   * @return The amountCharged.
   */
  int getAmountCharged();

  /**
   * <code>uint32 amountReceived = 3;</code>
   * @return The amountReceived.
   */
  int getAmountReceived();

  /**
   * <code>uint32 amountReturned = 4;</code>
   * @return The amountReturned.
   */
  int getAmountReturned();

  /**
   * <code>.local.example.sample.api.grpc.v1.Receiver.RefundAttributesMethod refundAttributesMethod = 5;</code>
   * @return The enum numeric value on the wire for refundAttributesMethod.
   */
  int getRefundAttributesMethodValue();
  /**
   * <code>.local.example.sample.api.grpc.v1.Receiver.RefundAttributesMethod refundAttributesMethod = 5;</code>
   * @return The refundAttributesMethod.
   */
  local.example.sample.api.grpc.v1.Receiver.RefundAttributesMethod getRefundAttributesMethod();

  /**
   * <code>.local.example.sample.api.grpc.v1.Receiver.RefundAttributeStatus refundAttributesStatus = 6;</code>
   * @return The enum numeric value on the wire for refundAttributesStatus.
   */
  int getRefundAttributesStatusValue();
  /**
   * <code>.local.example.sample.api.grpc.v1.Receiver.RefundAttributeStatus refundAttributesStatus = 6;</code>
   * @return The refundAttributesStatus.
   */
  local.example.sample.api.grpc.v1.Receiver.RefundAttributeStatus getRefundAttributesStatus();
}
