// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package local.example.sample.api.grpc.v1;

public interface UpdateChargeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.sample.api.grpc.v1.UpdateChargeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string chargeId = 1;</code>
   * @return The chargeId.
   */
  java.lang.String getChargeId();
  /**
   * <code>string chargeId = 1;</code>
   * @return The bytes for chargeId.
   */
  com.google.protobuf.ByteString
      getChargeIdBytes();

  /**
   * <code>string customerId = 2;</code>
   * @return The customerId.
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customerId = 2;</code>
   * @return The bytes for customerId.
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string receiptEmail = 4;</code>
   * @return The receiptEmail.
   */
  java.lang.String getReceiptEmail();
  /**
   * <code>string receiptEmail = 4;</code>
   * @return The bytes for receiptEmail.
   */
  com.google.protobuf.ByteString
      getReceiptEmailBytes();
}
