/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.example.spread.api;

public class Library {

    public String someString() {
        return "from Spread API!";
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
