---
openapi: 3.0.3
info:
  title: openapi-sample API
  version: 1.0.0-SNAPSHOT
paths:
  /sample:
    get:
      tags:
      - Sample Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
    put:
      tags:
      - Sample Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
    post:
      tags:
      - Sample Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
    delete:
      tags:
      - Sample Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
components:
  schemas:
    Sample:
      type: object
      properties:
        name:
          type: string
        definition:
          type: string
