// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

package local.example.care.item.api.grpc.v1;

public interface ItemCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:local.example.care.item.api.v1.ItemCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
